# =============================================================================
# Sink / writer module.
#
# This module contains all output logic for the Spark Structured Streaming job.
#
# It writes data to:
#
#   1. PostgreSQL
#      - Raw customer events
#      - Windowed event-type metrics
#
#   2. Parquet lake layers
#      - Bronze layer: raw Kafka JSON
#      - Silver layer: cleaned structured events
#
# Note:
#   Gold Parquet is intentionally disabled for now because Parquet does not
#   support Spark Streaming "update" output mode directly for aggregations.
#   Gold metrics are currently written to PostgreSQL using foreachBatch.
# =============================================================================

from config import (
    POSTGRES_URL,
    POSTGRES_USER,
    POSTGRES_PASSWORD,
    POSTGRES_DRIVER,
    RAW_EVENTS_TABLE,
    WINDOW_METRICS_TABLE,
    BRONZE_PATH,
    SILVER_PATH,
    REJECTED_EVENTS_TABLE,
)


# =============================================================================
# PostgreSQL sinks
# =============================================================================

def write_raw_events_to_postgres(batch_df, batch_id):
    """
    Write raw/cleaned event micro-batches to PostgreSQL.

    This function is used with Spark Structured Streaming foreachBatch.

    Parameters:
        batch_df:
            A Spark DataFrame representing one micro-batch of streaming data.

        batch_id:
            The unique ID of the micro-batch generated by Spark.

    Target table:
        customer_events

    Write mode:
        append

    Why append?
        Every event is a new record, so we keep adding rows.
    """

    batch_df.write \
        .format("jdbc") \
        .option("url", POSTGRES_URL) \
        .option("dbtable", RAW_EVENTS_TABLE) \
        .option("user", POSTGRES_USER) \
        .option("password", POSTGRES_PASSWORD) \
        .option("driver", POSTGRES_DRIVER) \
        .mode("append") \
        .save()


def write_window_metrics_to_postgres(batch_df, batch_id):
    """
    Write windowed aggregation metrics to PostgreSQL.

    This function receives aggregated rows such as:

        window_start | window_end | event_type | event_count

    Example:
        2026-05-09 10:00 | 2026-05-09 10:05 | purchase | 25

    This function is also used with foreachBatch.

    Target table:
        event_type_window_metrics

    Important:
        The upstream streaming query uses outputMode("update").
        That means Spark only sends updated aggregation results for windows
        that changed in the current micro-batch.

    Write mode:
        append

    Why append?
        For this learning project, we append every emitted update.
        Later, this can be improved with upsert logic to avoid duplicate
        window rows.
    """

    batch_df.write \
        .format("jdbc") \
        .option("url", POSTGRES_URL) \
        .option("dbtable", WINDOW_METRICS_TABLE) \
        .option("user", POSTGRES_USER) \
        .option("password", POSTGRES_PASSWORD) \
        .option("driver", POSTGRES_DRIVER) \
        .mode("append") \
        .save()

def write_rejected_events_to_postgres(batch_df, batch_id):
    """
    Write rejected events to PostgreSQL for auditing.

    This function is used with Spark Structured Streaming foreachBatch.

    Target table:
        rejected_events

    Write mode:
        append

    Why append?
        We want to keep a historical record of all rejected events for auditing.
    """

    batch_df.write \
        .format("jdbc") \
        .option("url", POSTGRES_URL) \
        .option("dbtable", REJECTED_EVENTS_TABLE) \
        .option("user", POSTGRES_USER) \
        .option("password", POSTGRES_PASSWORD) \
        .option("driver", POSTGRES_DRIVER) \
        .mode("append") \
        .save()


# =============================================================================
# Lakehouse / Parquet sinks
# =============================================================================

def write_bronze_to_parquet(df):
    """
    Define the Bronze layer Parquet sink.

    Bronze layer purpose:
        Store raw Kafka messages as received.

    Typical Bronze data:
        raw_value

    Why Bronze?
        - Preserve original data
        - Support replay/debugging
        - Protect against schema evolution
        - Keep an immutable raw copy

    This function returns a DataStreamWriter.
    The caller is responsible for adding:
        - outputMode(...)
        - checkpointLocation(...)
        - start()
    """

    return df.writeStream \
        .format("parquet") \
        .option("path", BRONZE_PATH)


def write_silver_to_parquet(df):
    """
    Define the Silver layer Parquet sink.

    Silver layer purpose:
        Store parsed, cleaned, structured customer events.

    Typical Silver columns:
        user_id
        event_type
        product_id
        event_time

    Bronze → Silver transformations:
        - Cast Kafka binary value to string
        - Parse JSON
        - Apply schema
        - Extract columns
        - Rename timestamp to event_time

    This function returns a DataStreamWriter.
    The caller is responsible for adding:
        - outputMode(...)
        - checkpointLocation(...)
        - start()
    """

    return df.writeStream \
        .format("parquet") \
        .option("path", SILVER_PATH)